services:
  - type: web
    name: oioi
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        sync: false
      - key: SQLALCHEMY_DATABASE_URI
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: RENDER
        value: true
      - key: FLASK_ENV
        value: production
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false

databases:
  - name: oioi-db
    databaseName: oioi
    plan: free 